package SHC_Schema;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CARD".
 */
public class Card {

    private Long id;
    /** Not-null value. */
    private String text;
    private Integer n_card;
    private Integer id_g;

    public Card() {
    }

    public Card(Long id) {
        this.id = id;
    }

    public Card(Long id, String text, Integer n_card, Integer id_g) {
        this.id = id;
        this.text = text;
        this.n_card = n_card;
        this.id_g = id_g;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(String text) {
        this.text = text;
    }

    public Integer getN_card() {
        return n_card;
    }

    public void setN_card(Integer n_card) {
        this.n_card = n_card;
    }

    public Integer getId_g() {
        return id_g;
    }

    public void setId_g(Integer id_g) {
        this.id_g = id_g;
    }

}
