package SHC_Schema;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import SHC_Schema.Card;
import SHC_Schema.GroupCard;

import SHC_Schema.CardDao;
import SHC_Schema.GroupCardDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cardDaoConfig;
    private final DaoConfig groupCardDaoConfig;

    private final CardDao cardDao;
    private final GroupCardDao groupCardDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cardDaoConfig = daoConfigMap.get(CardDao.class).clone();
        cardDaoConfig.initIdentityScope(type);

        groupCardDaoConfig = daoConfigMap.get(GroupCardDao.class).clone();
        groupCardDaoConfig.initIdentityScope(type);

        cardDao = new CardDao(cardDaoConfig, this);
        groupCardDao = new GroupCardDao(groupCardDaoConfig, this);

        registerDao(Card.class, cardDao);
        registerDao(GroupCard.class, groupCardDao);
    }
    
    public void clear() {
        cardDaoConfig.getIdentityScope().clear();
        groupCardDaoConfig.getIdentityScope().clear();
    }

    public CardDao getCardDao() {
        return cardDao;
    }

    public GroupCardDao getGroupCardDao() {
        return groupCardDao;
    }

}
