package SHC_Schema;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GROUP_CARD".
 */
public class GroupCard {

    private Long id;
    /** Not-null value. */
    private String name;
    private Integer amount_cards;

    public GroupCard() {
    }

    public GroupCard(Long id) {
        this.id = id;
    }

    public GroupCard(Long id, String name, Integer amount_cards) {
        this.id = id;
        this.name = name;
        this.amount_cards = amount_cards;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Integer getAmount_cards() {
        return amount_cards;
    }

    public void setAmount_cards(Integer amount_cards) {
        this.amount_cards = amount_cards;
    }

}
