package com.ayoprez.speechhelpcards;

/**
 * Created by AyoPrez on 2/08/15.
 */
public class Texts {

    public String dozenText = "1.The battery is always a problem in smartphones, because these last less than we would like. With this new feature, Google try to do something in the software side to solve the problem. Doze mode monitors when the device isn't being used to put it into a deep sleep which uses less power and can double the battery life. Of course, it is not something you can switch on or switch off. ";
    public String androidPayText = "2.After the good acceptance of Apple Pay, Google has presented its own contactless payment system, Android Pay. It is just a way to pay using you phone, digitally  or physically. With Android Pay you can go to a shop and pay using the NFC technology, but it also has an API, so the developer can introduce a button to pay in an app thought Android Pay.";
    public String fingerprintText = "3.And, to help Android Pay, Android M add support for fingerprint scanner. So, the developer can introduce in its apps a fingerprint recognition, but right now only a couple of devices have fingerprint scanner. Qualcomm, the company that makes the microprocessor and some chips of a lot of current mobiles, has presented a new technology to use the screen of the device as fingerprint scanner, using ultrasonic to make a 3D scanner of the finger. ";
    public String permissionsText = "4.One of the most popular new feature in Android M. Before Android M, when you download an app, you had to accept all the permissions, even if you don't want it. With Android M you are able to choose which permission accept or which not. You  can, anytime, go to the settings of the app and switch on or switch off the different permissions of the app. Knowing that, the developer of the app should only include the necessary permissions. Also have to include in the app, when it is necessary, a dialog requesting to activate a concrete permission if it is off, and control the possible negative answer of the user. ";
    public String shareDirectText = "5.Another little change, but that can facilitate to the user to share content faster is the new Direct share function. With this, the phone recognize the people who the user more often share content with, and put it directly in the share menu. This is not automatic, the developer has to do some thing to introduce it in the app and make it available.";
    public String bluetoothDetection = "6.In Android M, Google is improving the way apps scan for Bluetooth Low Energy devices. The developer can make that the apps use the new function to only be notified when an advertisement packet matching the set ScanFilter is first found, and when it is not seen for a period of time. This approach to scanning is more power-efficient than what’s provided in the previous platform version. I don't use very often the bluetooth of my device, and I don't understand very well this feature, but I though it was important to be named here. ";
    public String bleLocation = "7.With the last version of Jelly Beans, Android 4.3, Google implemented the idea of get your location using the WiFi network, even if the WiFi is off in the device. Android M go a step further and add the Bluetooth scanning in the equation. So, the user can activate the bluetooth scanning location and look for bluetooth low energy devices like beacons to get a faster location fix.  This may be useful inside malls, airports or indoor locations where the reach and dispersion of beacons can be better than the GPS signal";
}
